/* ORA_CLOUD.JS - BUILD: 6th March 2014 version 2.21 */
/* Tagging script setup */
var tagControl=new Array();tagControl.isTest=s_checkdev();tagControl.ora_local="ora_code_cloud.js";tagControl.ora_global="ora_code.js";tagControl.ora_path="/us/assets/metrics/";tagControl.ora_root=(tagControl.isTest)?"://www-portal-stage.oracle.com":"://www.oracleimg.com";tagControl["reportsuite-dev"]="oracledevcloud";tagControl["reportsuite-prod"]="oraclecloud,oracleglobal";tagControl.site="cloud";tagControl.lang="en-us";tagControl.codeversion="2.21";tagControl.elq_global="elqCfg.min.js";tagControl.elq_path="/i/";tagControl.elq_root="//img03.en25.com";tagControl.elq_prodID="1973398186";tagControl.elq_devID="30554202";tagControl.clevel=consentStatus();tagControl.host_type=(window.location.protocol.toLowerCase().indexOf("https")!=-1)?"https":"http";tagControl.eloqua_OK=false;tagControl.adobe_OK=(tagControl.clevel!=1);
/* Global variables */
var s_pageName="";var s_pingOK=true;
/* Eloqua Site Tags and Functions */
if(tagControl.eloqua_OK){var _elqQ=_elqQ||[];_elqQ.push(["elqSetSiteId",tagControl.elq_prodID]);_elqQ.push(["elqTrackPageView"]);_elqQ.push(["elqSetSiteId",tagControl.elq_devID]);_elqQ.push(["elqTrackPageView"]);(function(){function async_load(){var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src=tagControl.elq_root+tagControl.elq_path+tagControl.elq_global;var x=document.getElementsByTagName("script")[0];x.parentNode.insertBefore(s,x);}if(window.addEventListener){window.addEventListener("DOMContentLoaded",async_load,false);}else{if(window.attachEvent){window.attachEvent("onload",async_load);}}})();
/* Site Catalyst Tags and Functions */
}if(tagControl.adobe_OK){if(typeof s_pageName=="undefined"){var s_pageName="";}document.write("<script type='text/javascript' src='"+tagControl.host_type+tagControl.ora_root+tagControl.ora_path+tagControl.ora_global+"'><\/script>");function s_setAccount(){var sa=["oracledevall","cloud","en-us"];sa[0]=(tagControl.isTest)?tagControl["reportsuite-dev"]:tagControl["reportsuite-prod"];sa[1]=tagControl.site;sa[2]=tagControl.lang;return sa;}function s_oraVer(_s,_v){_v=_s+_v;oraVersion=(oraVersion.indexOf(_s)==-1)?oraVersion+_v:oraVersion.substr(0,oraVersion.indexOf(_s))+_v;}function gotjQ(){try{var jq=(jQuery)?true:false;}catch(err){var jq=false;}return jq;}function s_rePingCloud(_in){s_pageName=s.pageName=s_account[1]+":"+s_account[2]+":"+_in;s.eVar27=s.pageName;if(s.pageName.toLowerCase().indexOf("account")!=-1){s.events=s.apl(s.events,"event26",",",1);}if(s.pageName.toLowerCase().indexOf("summary")!=-1){s.events=s.apl(s.events,"event27",",",1);}s_Ping(true);s.events="";}function getUserInfo(){var USER=new Object();this.value_enc=getCookieData("ORA_UCM_INFO");this.array=this.value_enc.split("~");USER.guid=sani(this.array[1]);USER.username=sani(this.array[4]);return USER;}function getCookieData(label){var labelLen=label.length;var cLen=document.cookie.length;var i=0;var cEnd;while(i<cLen){var j=i+labelLen;if(document.cookie.substring(i,j)==label){cEnd=document.cookie.indexOf(";",j);if(cEnd==-1){cEnd=document.cookie.length;}j++;return decodeURIComponent(document.cookie.substring(j,cEnd).replace("+","%20"));}i++;}return"";}
/* Site Specific Functions */
function s_prePlugins(s){s_oraVer(":"+tagControl.site+":",tagControl.codeversion);s.pageName=(typeof(s_pageName)=="undefined"||s_pageName=="")?cloudpageName(document.title):s_pageName;s_pageName=s.pageName;}function s_postPlugins(s){if(typeof USER=="undefined"){var USEROK=new getUserInfo();if(USEROK.username!="NoData"){USER=new getUserInfo();}if(window.s_setGUID){s_setGUID();}}}function cloudpageName(pn){var splitBy=["|"];var dirDelim="/";var s_pn=s_account[1]+":"+s_account[2]+":";var siteName="oracle-cloud";for(var a=0;a<splitBy.length;a++){pn=pn.split(splitBy[a]);}for(a=0;a<pn.length;a++){pn[a]=pn[a].trim().replace(/ /g,"-").toLowerCase();}for(a=pn.length-1;a>-1;a--){if(pn[a].indexOf(siteName)==0){s_pn=s_pn+dirDelim;}else{s_pn=s_pn+pn[a]+dirDelim;}}if(document.location.href.toLowerCase().indexOf(".oracle.com/home")!=-1){s_pn=s_account[1]+":"+s_account[2]+":/home";}return s_pn;}function setDivs(){_a=[["a#uLogo","header"],["div.cloudLogo","header"],["ul#opcMobileNav","hnav"],["ul.opcNav","hnav"],["li.signInLink","hnav","signin"],["div.chat-tab","side-tab","chat"],["div.contact-tab","side-tab","contact"],["div.cloudButton","button"],["div.flex-control-nav","heronav-radio"],["div.service-name-summary-tab","service-name-summary-tab"],["div.resourcesSideNav","resourcessidenav"],["div.cloud-banner-container","hero-container"],["div.cloud-banner-section","hero-section"],["div.servicepreviewhomebanner","servicepreviewhomebanner"],["div.category-tab-title","category-tab-title"],["a.LearnMoreTab","LearnMoreTab"],["a.OverviewTab","OverviewTab"],["div.footerLeft","footer"],["div.footerRight ","socialicons"]];return _a;}
/* jQuery Click Tracking */
if(gotjQ()){jQuery(document).ready(function($){var trackas=setDivs();var sn=s_setAccount()[1];var ln=s_setAccount()[2];for(var i=0;i<trackas.length;i++){if(!$(trackas[i][0]).attr("data-trackas")&&trackas[i][1]){$(trackas[i][0]).attr("data-trackas",trackas[i][1]);}if(trackas[i][2]&&trackas[i][2]=="resetpage"){$(trackas[i][0]).attr("data-pgreset","true");}else{if(trackas[i][2]&&!$(trackas[i][0]).attr("data-lbl")){$(trackas[i][0]).attr("data-lbl",trackas[i][2]);}}}$(document).on("click","*[data-trackas] a,a[data-trackas]",function(e){var lbl="";var o=$(this);if(o.attr("data-lbl")!="notrack"){if(o.attr("data-lbl")){lbl=o.attr("data-lbl");}else{if(o.attr("name")){lbl=o.attr("name");}else{if(o.attr("title")){lbl=o.attr("title");}else{if(o.find("img")&&o.find("img").first().attr("title")){lbl=o.find("img").first().attr("title");}else{if(o.find("img")&&o.find("img").first().attr("alt")){lbl=o.find("img").first().attr("alt");}else{if(o.find("img").first().attr("src")){lbl=o.find("img").first().attr("src");lbl=lbl.split("/")[(lbl.split("/").length-1)];}else{lbl=o.text();}}}}}}lbl=lbl.trim();var d=o.closest("[data-trackas]").attr("data-trackas");d=(d=="hnav"||d=="header")?":":"-";if(!o.attr("data-trackas")){while(o.parent()){o=o.parent();if(o.attr("data-lbl")){lbl=o.attr("data-lbl")+d+lbl;}if(o.attr("data-trackas")){break;}}}lbl=lbl.toLowerCase().replace(/ /g,"-").replace(/-+/g,"-");var sec=(o.attr("data-trackas"))?o.attr("data-trackas"):o.closest("*[data-trackas]").attr("data-trackas");navTrack(sn,ln,sec,lbl);if(o.attr("data-pgreset")=="true"){s.clearVars();if(o.attr("href").indexOf("#")==0&&s.pageName){if(!$("body").attr("data-pgname")){$("body").attr("data-pgname",s.pageName);var pn=s.pageName;}else{var pn=$("body").attr("data-pgname");}s.pageName=pn+"/"+o.attr("href").split("#")[1];}else{s_orapageName(o.attr("href"));}var s_code=s.t();if(s_code){document.write(s_code);}}}});});}
/* General Functions */
}function consentStatus(){var cStatus=0;if(typeof(trustchk)=="undefined"){try{var trustchk=truste.cma.callApi("getConsentDecision","oracle.com");}catch(err){cStatus=-1;}}cStatus=(cStatus!=-1)?trustchk.consentDecision:cStatus;return cStatus;}function s_checkdev(){var isDev=false;var devSites=new Array();devSites=["-stage","stg-","-dev","-content","localhost","127.0.0.1",".us.oracle.com"];var al=devSites.length;for(i=0;i<al;i++){if(location.href.indexOf(devSites[i])!=-1){isDev=true;i=al+1;}}return(isDev);}
/* End Tags */
